add prune as a seperate job

diff --git a/templates/restic_script_Linux.j2 b/templates/restic_script_Linux.j2
--- a/templates/restic_script_Linux.j2
+++ b/templates/restic_script_Linux.j2
@@ -6,9 +6,11 @@
 {% if item.disable_logging is defined and item.disable_logging %}
 {% set backup_result_log, backup_output_log = "/dev/null", "/dev/null" %}
 {% set forget_result_log, forget_output_log = "/dev/null", "/dev/null" %}
+{% set prune_result_log, prune_output_log = "/dev/null", "/dev/null" %}
 {% else %}
 {% set backup_result_log, backup_output_log = restic_log_dir + "/" + item.name + "-backup-result.log", restic_log_dir + "/" + item.name + "-backup-output.log" %}
 {% set forget_result_log, forget_output_log = restic_log_dir + "/" + item.name + "-forget-result.log", restic_log_dir + "/" + item.name + "-forget-output.log" %}
+{% set prune_result_log, prune_output_log = restic_log_dir + "/" + item.name + "-prune-result.log", restic_log_dir + "/" + item.name + "-prune-output.log" %}
 {% endif %}
 
 export RESTIC_REPOSITORY={{ restic_repos[item.repo].location }}
@@ -78,66 +80,72 @@ set -uxo pipefail
 {%- endmacro %}
 
 {% macro exclude(exclude) %}
-    {% if exclude.exclude_cache is defined and exclude.exclude_cache == true %}
-        --exclude-cache \
-    {% endif %}
-    {% if exclude.exclude is defined %}
-        {% for path in exclude.exclude %}
-            --exclude {{ path }} \
-        {% endfor %}
-    {% endif %}
-    {% if exclude.iexclude is defined %}
-        {% for path in exclude.iexclude %}
-            --iexclude {{ path }} \
-        {% endfor %}
-    {% endif %}
-    {% if exclude.exclude_file is defined %}
-        {% for path in exclude.exclude_file %}
-            --exclude-file {{ path }} \
-        {% endfor %}
-    {% endif %}
-    {% if exclude.exclude_if_present is defined %}
-        {% for path in exclude.exclude_if_present %}
-            --exclude-if-present {{ path }} \
-        {% endfor %}
-    {% endif %}
+  {% if exclude.exclude_cache is defined and exclude.exclude_cache == true %}
+  --exclude-caches \
+  {% endif %}
+  {% if exclude.exclude is defined %}
+    {% for path in exclude.exclude %}
+  --exclude {{ path }} \
+    {% endfor %}
+  {% endif %}
+  {% if exclude.iexclude is defined %}
+    {% for path in exclude.iexclude %}
+  --iexclude {{ path }} \
+    {% endfor %}
+  {% endif %}
+  {% if exclude.exclude_file is defined %}
+    {% for path in exclude.exclude_file %}
+  --exclude-file {{ path }} \
+    {% endfor %}
+  {% endif %}
+  {% if exclude.exclude_if_present is defined %}
+    {% for path in exclude.exclude_if_present %}
+  --exclude-if-present {{ path }} \
+    {% endfor %}
+  {% endif %}
 {% endmacro %}
 {#
   Define backup commands
 #}
-if [[ -z ${CRON+x} ]]; then
-  MODE_TAG="--tag manual"
-else
-  MODE_TAG="--tag cron"
-fi
-
+if [[ -z ${PRUNE+x} ]]; then
+  if [[ -z ${CRON+x} ]]; then
+    MODE_TAG="--tag manual"
+  else
+    MODE_TAG="--tag cron"
+  fi
 {% if item.stdin is defined and item.stdin == true %}
-  {{ item.stdin_cmd }} | {{ restic_install_path }}/restic backup \
+  {{ item.stdin_cmd }} | {{ restic_install_path }}/restic backup --verbose={{ item.verbose|default(0) }} \
     --stdin $MODE_TAG \
     {{ tags(item.tags) }} \
     {{ stdin_filename(item.stdin_filename) }} \
     {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
     $@ \
 {% else %}
-  {{ restic_install_path }}/restic backup $BACKUP_SOURCE $MODE_TAG \
+  {{ restic_install_path }}/restic backup $BACKUP_SOURCE $MODE_TAG --verbose={{ item.verbose|default(0) }} \
     {{ tags(item.tags) }} \
     {% if item.exclude is defined %}{{ exclude(item.exclude) }}{% endif %} \
     $@ \
 {% endif %} | tee {{ backup_output_log }}
-if [[ $? -eq 0 ]]
-then
+  if [[ $? -eq 0 ]]; then
     echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ backup_result_log }}
-else
+  else
     echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ backup_result_log }}
-fi
+  fi
 
 {#
   Define stdin forget commands
 #}
-{{ restic_install_path }}/restic forget --path {{ path(item) }} {{ retention_pattern(item) }} {% if item.prune is defined and item.prune == true %}--prune{% endif %} | tee {{ forget_output_log }}
-if [[ $? -eq 0 ]]
-then
+  {{ restic_install_path }}/restic forget --path {{ path(item) }} {{ retention_pattern(item) }} {% if item.prune_forget is defined and item.prune_forget == true %}--prune{% endif %} --verbose={{ item.verbose|default(0) }} | tee {{ forget_output_log }}
+  if [[ $? -eq 0 ]]; then
     echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ forget_result_log }}
-else
+  else
     echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ forget_result_log }}
+  fi
+else
+  {{ restic_install_path }}/restic prune --verbose={{ item.verbose|default(0) }} | tee {{ prune_output_log }}
+  if [[ $? -eq 0 ]]; then
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') OK" >> {{ prune_result_log }}
+  else
+    echo "$(date -u '+%Y-%m-%d %H:%M:%S') ERROR" >> {{ prune_result_log }}
+  fi
 fi
